### ISSUE TITLE
Any plan to upgrade to 0.10.x version?

### ISSUE THREAD

**Issue by gharia** [gjovanov/docker#1]

**Comment by gjovanov** [comment]
@gharia since you didn't specify what exaclty would you like to have upgrades, i've made the assumption, that you were talking about `janus` so I have aupgraded both: `janus-alpine` and `janus-slim` to version `0.10.3`.

Pls confirm that this was the request in which case feel free to close this issue.

**Comment by gjovanov** [comment]
since didn't receive a response @gharia , I'm closing this issue. Feel free to reopen

**Comment by gharia** [comment]
Sorry @gjovanov for missing this one. But yeah, I was talking about updating Janus version. Thanks for your efforts. I have been using this container in staging. Till now no issue.
